backend:
  name: github
  branch: main # change this to your branch
  repo: Tdnshah/thehigglers # change this to your repo
  site_domain: thehigglers.com # change this to your domain
  base_url: https://thehigglers.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration
media_folder: "/public"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "type", name: "type", widget: "hidden", default: 'blog'}
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/SingleBlog.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Updated Date", name: "lastmod", widget: "datetime"}
      - {label: "Featured Image", name: "image_link", widget: "image"}
      - {label: "Status", name: "status", widget: "select", options: ["draft", "review", "published"]}
      - {label: 'Add Blog Tags', name: 'tags', widget: 'list', field: {label: Tags, name: tagsList, widget: 'relation', collection: categories, searchFields: ["category"],search_fields: ["category"]  , valueField: "category",value_Field: "category"}}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "src/pages/blogs/tags/" # The path to the folder where the documents are stored
    create: true
    fields: 
      - {label: 'Category', name: category, widget: string}

